[package]
org = "dinuka_amarasinghe"
name = "social_media"
version = "0.1.0"
distribution = "2201.9.0-20240419-152500-bd530dd2"

[build-options]
observabilityIncluded = true

[[tool.persist]]
id = "generate-db-client"
targetModule = "social_media.cache"
options.datastore = "redis"
filePath = "persist/model.bal"

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "persist.redis-native"
version = "0.1.0-SNAPSHOT"

